### ISSUE TITLE
Some documentation typos (file fmt.mli)

### ISSUE THREAD

**Issue by Fourchaux** [dbuenzli/fmt#10]
L088 : /int32/uint32/
L106 : /pp_float_dsig/float_dsig/
L209 : /botttom/bottom/
L241 : /brackets/braces/
L246 : /pp_text/text/
L250 : /pp_lines/lines/
L277 : /pp_byte_size/byte_size/
L282 : /pp_bi_byte_size/bi_byte_size/

**Comment by dbuenzli** [comment]
Thanks fixed by 2796b7a9d5f40bea
