### ISSUE TITLE
`Fmt_tty`'s interface is exported in the `fmt` library

### ISSUE THREAD

**Issue by Drup** [dbuenzli/fmt#12]
The implementation is not (thankfully).

**Comment by dbuenzli** [comment]
Should I do something ? I think that's a general issue with most ocamlfind subpackages (not that I'm not willing to fix it, just trying to make sure we talk about the same problem).

**Comment by dbuenzli** [comment]
> I think that's a general issue with most ocamlfind subpackages

To be precise, the *way* they are defined, it's not an ocamlfind problem in itself.
