### ISSUE TITLE
The type of Fmt.unit is wrong

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/fmt#14]
It is: 
```ocaml
val unit : (unit, Format.formatter, unit) Pervasives.format -> unit t
```
Which prevents for example to write: 
```ocaml
Fmt.(option (prefix (unit " ") pp_type)) 
```
It should be 
```ocaml
val unit : string -> unit t
```

**Comment by Drup** [comment]
Wait, why doesn't it work with `" "` ?

**Comment by Drup** [comment]
It works just fine for me. Any constant string is a constant format.

**Comment by dbuenzli** [comment]
That's odd.

**Comment by Drup** [comment]
I remember advocating this precise type, because it allows you to write `Fmt.list ~sep:(unit "@,") ...`.

**Comment by dbuenzli** [comment]
Ah yes. Wait, checking again.

**Comment by dbuenzli** [comment]
Grunch. It works indeed. I don't know why but it seems that in certain cases. The type checker annoys me with string vs format. I'll revert the commit.

**Comment by dbuenzli** [comment]
Thanks for paying attention...

**Comment by Drup** [comment]
There are two cases I can see that would lead to confusion:
1) `let s = "bla" in Fmt.unit s`
2) `In case of type error over the *returned* type, the error message will be messy. `(Fmt.unit " " : string Fmt.t)`.
