### ISSUE TITLE
Styled formatting is not flexible

### ISSUE THREAD

**Issue by Drup** [dbuenzli/fmt#2]
Currently, styled formatting is done by (conditionally) outputting terminal escape sequences. This means that there are two choices currently: 
- Output on something that understand escape sequences and enable styling
- Do not style at all.

However, using `Format.tag`, it is possible to have customizable interpretation depending on the output formatter (one being escape sequence). 
The upside is that it could output styled things on various outputs (html, lambda_term, etc), given the correct interpretation of tags (which doesn't need to be provided in `fmt`). 
The downside is that enabling styling must be done for each output formatter.

It's something I did for lambda_term once. The implementation was a bit awkward but the interface ended up being rather simple (one `pp` function, like you have currently).

**Comment by dbuenzli** [comment]
I don't mind adding a few other backends that do not introduce dependencies if that's your problem. I tried to use `Format.tag` at a certain point but 1) I found the whole thing rather confusing 2) It's not a compositional approach.

**Comment by Drup** [comment]
I agree it's extremely confusing, but fortunately, you can hide most of the complexity.

It should be possible to provide a nicer interface by getting/setting the formatter_tag_functions and composing the functions under the hood. 

Maybe something like that ?
```ocaml
type tag_function : `Mark of (tag -> string) | `Print of tag t | `Nothing
val add_tag_functions : open:tag_function -> close:tag_function -> formatter -> unit
```

**Comment by dbuenzli** [comment]
> The upside is that it could output styled things on various outputs (html, lambda_term, etc), given the correct interpretation of tags (which doesn't need to be provided in fmt).

I still think that this idea is completely broken, as you can't match the semantics of tags and some backends may not express that using tags. What we really want is per formatter user definable and setable metadata. https://github.com/dbuenzli/fmt/issues/6 should be however solved.
