### ISSUE TITLE
Fmt.exn_backtrace crashes when backtraces are off

### ISSUE THREAD

**Issue by talex5** [dbuenzli/fmt#23]
If compiled without debug symbols or run without `OCAMLRUNPARAM=b`, `Printexc.raw_backtrace_to_string` returns the empty string. `Fmt.exn_backtrace` then crashes with `exception Invalid_argument("index out of bounds")`.

Also, if backtraces are on then it loses the last character of the error message. e.g.

```
let test_bt () =
  try failwith "Test"
  with ex ->
    let bt = Printexc.get_raw_backtrace () in
    Fmt.pr "[%s]@." (Printexc.raw_backtrace_to_string bt);
    let msg = Fmt.strf "%a" Fmt.exn_backtrace (ex, bt) in
    print_endline msg
```

prints

```
[Raised at file "pervasives.ml", line 32, characters 17-33
Called from file "test/test.ml", line 36, characters 6-21
]
Exception: Failure("Test")
Raised at file "pervasives.ml", line 32, characters 17-33
Called from file "test/test.ml", line 36, characters 6-2
```

(tested with OCaml 4.04.0)

**Comment by dbuenzli** [comment]
Thanks for the report and sorry for the stupid bugs.
