### ISSUE TITLE
Add Fmt.{invalid_arg,failwith}

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/fmt#24]
Raising the corresponding exceptions.

```ocaml
val Fmt.failwith : ('a, Format.formatter, unit, unit) format4 -> 'a
val Fmt.invalid_arg : ('a, Format.formatter, unit, unit) format4 -> 'a
```

**Comment by hcarty** [comment]
I'd love to have this in Fmt! If you're not working on it would you accept a PR? Implementation-wise, is using `Fmt.kstrf` the right approach?

**Comment by dbuenzli** [comment]
Yes and please do. You can add them in their own section after [this one](http://erratique.ch/software/fmt/doc/Fmt.html#fmt). I'd suggest  `{1:fmt_exns Formatting exceptions}` as a section title.
