### ISSUE TITLE
Add Fmt.nl

### ISSUE THREAD

**Issue by rizo** [dbuenzli/fmt#28]
What do you think about this small newline format combinator?

```ocaml
let nl = Format.pp_print_newline
```

Which can be used like this:

```ocaml
# Fmt.(pr "%a" (list ~sep:nl int) [1; 2; 3])
1
2
3
```

**Comment by dbuenzli** [comment]
> What do you think about this small newline format combinator?

I think it's bad, that's not the way formatters should be used, it kills compositionality (see also #26). The way of writing what you want is by using a vertical box: 

```ocaml
Fmt.(pr "@[<v>%a@]" (list int) [1; 2; 3]);;
1                                                                                                                                      
2                                                                                                                                      
3
```
or 
```ocaml
# Fmt.(pr "%a" (vbox @@ list int) [1; 2; 3]);;
1                                                                                                                                      
2                                                                                                                                      
3
```

**Comment by rizo** [comment]
On a related note, before I open a new issue...

Would a `Fmt.pl` and `Fmt.epl` be acceptable for alternatives to `Fmt.pr` and `Fmt.epr` that append `@.` to the format?

I've seen people (myself including) forget to add `@.` way too many times and then wonder why the output is not flushed.

Unlike the originally proposed combinator, this one does not break composition as it only happens at the top-level.

Happy to submit a PR if you're ok with this addition.

**Comment by dbuenzli** [comment]
Wasn't that discussed in https://github.com/dbuenzli/fmt/issues/26 ?

**Comment by rizo** [comment]
Missed that one. After reviewing the thread:

- I don't see how `Fmt.pl`/`Fmt.epl` would break composability – the full format is already formed at the moment of printing;
  - But yes, having `Fmt.fpl` would break composability and should not be added;
- No amount of documentation will solve the fact that users forget to add `@.` or `\n`.
- Not trusting the user to know the difference between `Fmt.pr` and `Fmt.pl` seems strange.
