### ISSUE TITLE
Fmt.kstrf doesn't like partial application

### ISSUE THREAD

**Issue by samoht** [dbuenzli/fmt#29]
The following program gives an assert failure:

```ocaml
let parse fmt = Fmt.kstrf (fun x -> x) fmt

let check f = assert (f "X" = f "X")

let () = check (parse "%s")
```

This is fixed if you replace `Fmt.kstrf` by `Format.ksprintf`. This is fixed if you eta-expand `(parse "%s")` into `(fun x -> parse "%s" x)`. Not sure exactly what is happening there ...

**Comment by dbuenzli** [comment]
A `Buffer.reset` is missing on [this line](https://github.com/dbuenzli/fmt/blob/b79dc14f8a6edd8ca2e6e23fe8c64c09852cb2d1/src/fmt.ml#L18) to protect whenever the internal buffer ends up being reused.

**Comment by dbuenzli** [comment]
[Here](https://github.com/dbuenzli/fmt/blob/b79dc14f8a6edd8ca2e6e23fe8c64c09852cb2d1/src/fmt.ml#L454) aswell.
