### ISSUE TITLE
Question on howto use "fmt"

### ISSUE THREAD

**Issue by eiselekd** [dbuenzli/fmt#37]
(I'm a ocaml newbie)
I try to test the "fmt" module and ran into a problem. While "pam install fmt" seems to succeed, I cannot load it ```open Fmt;;``` :  ```Error: Unbound module Fmt```.
I tried to run the test/test.ml example but I dont really know howto compile it.

**Comment by dbuenzli** [comment]
Please ask these questions on https://discuss.ocaml.org/ where people are willing to help newcomers. Also formulate them with a little bit more details about the context. 

Presumably you are trying to do this from the `ocaml` (or `utop`) toplevel. This should do:
```
#use "topfind"
#require "fmt"
```

**Comment by eiselekd** [comment]
In the REPL I can use "#require "fmt" however when using ```ocamlc``` the modules is not found.

**Comment by dbuenzli** [comment]
Try something like `ocamlfind ocamlc -package fmt yourfile.ml` but please continue that discussion on discuss.ocaml.org.

**Comment by eiselekd** [comment]
ok thanks

**Comment by eiselekd** [comment]
Sorry, just one more comment. I now tried "pkg/pkg.ml build" and copied the _build/src/* to ".opam/default/lib/fmt/" and then I can run "open Fmt;;". Seems to be some incompatibility of the opam binary files of fmt....

**Comment by dbuenzli** [comment]
Don't do these things... and also what you inferred doesn't make any sense.

**Comment by dbuenzli** [comment]
Here's a [small tutorial](https://ocaml.org/learn/tutorials/compiling_ocaml_projects.html) to compile things by hand and use libraries. But please these questions are OT for this issue tracker,  ask these questions on discuss.ocaml.org where it might benefit other newcomers aswell.
