### ISSUE TITLE
Change the name `Fmt.pp`

### ISSUE THREAD

**Issue by Drup** [dbuenzli/fmt#4]
When you have a recursive datastructure and you want to define a pretty printer for it (that you naturally call 'pp'), you end up with code like that:

```ocaml
let rec pp : t Fmt.t = fun fmt -> function
  | Mod d          -> Fmt.string fmt d#module_name
  | List (f, args) ->
    Fmt.pp fmt "%s%a"
      f#module_name
      Fmt.(parens @@ list pp) args
```
and then the last line is wrong, because of the local open.

I'm afraid the situation is going to be quite frequent. A name different than `pp` would probably be better ...

**Comment by samoht** [comment]
`Fmt.fp`?

**Comment by dbuenzli** [comment]
`Fmt.grrrr`.

**Comment by dbuenzli** [comment]
Here are a few candidates `Fmt.fp`, `Fmt.fpf`, `Fmt.fmt`, `Fmt.prf`, `Fmt.fprf`. If we assume we never expose `Format.printf` but let people use `Fmt.(prf stdout)` for that, I'm willing to go with `Fmt.prf` as it resonates with `Astring`'s `strf`.

**Comment by dbuenzli** [comment]
Or `Fmt.pf`

**Comment by Drup** [comment]
It might seems very audacious and novel, but why not `fprint` ? :]

It's not like we don't have tabcompletion.

**Comment by dbuenzli** [comment]
> It's not like we don't have tabcompletion.

It's not about writing. It's more that I prefer very short ids for these boring names so that your formatting instruction gets a better chance to fit on a single line, in 80 columns.

**Comment by Drup** [comment]
I know. And I do feel like `fprint` is short enough and completely conflict-proof.

**Comment by dbuenzli** [comment]
If we want it conflict proof then I think I prefer `Fmt.prcthulhu`.

**Comment by Drup** [comment]
I wanted to say something about choosing 2 to 4 random letters that do not form a pronounceable word, but you already exhausted that. :(

**Comment by Drup** [comment]
```
Error: Unbound value spf
Hint: Did you mean kpf, pf or sp?
```
:]
