### ISSUE TITLE
Consider dropping the unix dependency 

### ISSUE THREAD

**Issue by hhugo** [dbuenzli/fmt#51]
As far as I can see, `Fmt` only depends on unix for its `isatty` feature. 
The ocaml runtime has `caml_sys_isatty` which is what you want. It is used in the compiler but not exported in the `Stdlib`. Maybe it should.

**Comment by dbuenzli** [comment]
Does it pose a particular problem to you ? Formally the `fmt` library does not depend on `unix`, only `fmt.tty` does. 

> The ocaml runtime has `caml_sys_isatty` which is what you want. It is used in the compiler but not exported in the `Stdlib`. Maybe it should.

Can't dig out the discussion but I think there was agreement when it was introduced that it would not.

**Comment by dbuenzli** [comment]
I'm not too keen to depend on primitives that are not publicly exposed.

**Comment by dbuenzli** [comment]
I don't mind dropping the dependency if the primitive gets exposed in the stdlib (it would also certainly be very useful for cmdliner). So you know what to do now ;–)

**Comment by dbuenzli** [comment]
(Also I'm willing to use the primitive as soon as it gets clear that it will be exposed in the stdlib)
