### ISSUE TITLE
The git repository is missing the v0.9.0 tag

### ISSUE THREAD

**Issue by NathanReb** [dbuenzli/fmt#54]
Before I start let me thank you for maintaining `fmt`. Just as a lot of other OCaml developers, I use it quite extensively!

`fmt.0.9.0` has been released but it seems the corresponding git tag was not pushed either here or upstream at `https://erratique.ch/repos/fmt.git`. Could you please push the tag or eventually let me know the hash of the commit used to produce the release tarball?

To give you a bit of context, the reason why I'm asking for this is because we maintain dune ports of opam packages at https://github.com/dune-universe/opam-overlays to make them compatible with opam-monorepo. We want to make sure the dune ports are as close as possible to released version they correspond to.

Please let me know if I can help in any way with this.

**Comment by dbuenzli** [comment]
Indeed I often forget to push the last commit and/or tag in my repos after a release. This should be good now.
