### ISSUE TITLE
Fmt.styled doesn't return a formatter of the same type

### ISSUE THREAD

**Issue by terencode** [dbuenzli/fmt#55]
According to the documentation, applying `Fmt.styled` to a formatter returns one  of the same type : 
> val [style](https://erratique.ch/software/fmt/doc/Fmt/index.html#type-style)d : style -> 'a [t](https://erratique.ch/software/fmt/doc/Fmt/index.html#type-t) -> 'a [t](https://erratique.ch/software/fmt/doc/Fmt/index.html#type-t)
styled s pp formats like pp but styled with s.

but in practice,  the `'a` is replaced by unit : 
```ocaml
Format.formatter ->
('a, Format.formatter, unit, unit, unit, unit) format6 -> 'a
```
becomes 

```ocaml
Format.formatter ->
(unit, Format.formatter, unit, unit, unit, unit) format6 -> unit
```

and is thus only usable with simple strings.

Here is an example I would expect to work but doesn't : 

```ocaml
Fmt.set_style_renderer  Fmt.stdout `Ansi_tty;

let pf = Fmt.pf in
pf Fmt.stdout "Hello, %s\n" "World";
let pf = Fmt.styled `Red pf  in
pf Fmt.stdout "Hello, %s\n" "World"
```
I had the same behaviour on OCaml 4.08.1 & 4.14.0

**Comment by dbuenzli** [comment]
Not sure I understand you. The definition of `'a Fmt.t` is: 

```ocaml
type 'a t = Format.formatter -> 'a -> unit
```

**Comment by terencode** [comment]
Ok I might have wrongly understood how this works.
How would I go about doing what I want in the example, that is, print to stdout a formatted string with a specific style ?

**Comment by dbuenzli** [comment]
Something like that:

```ocaml
let pp_hello ppf n = Fmt.pf ppf "Hello %s" n
let pp_red_hello = Fmt.styled (`Fg `Red) pp_hello
let () = 
  let () = Fmt.set_style_renderer Fmt.stdout `Ansi_tty in 
  Fmt.pr "%a" pp_red_hello "World"
```

If you have further questions about using the library, please ask them on https://discuss.ocaml.org/ (you can log in with your github account).

**Comment by terencode** [comment]
Ok, thanks for your help. I will use discuss next time (I just created an account).
