### ISSUE TITLE
Make ANSI styling and UTF-8 control per formatter

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/fmt#6]
Doing it globally in the library is unacceptable. @Drup suggests abusing the formatter tag system. Related to #2.

**Comment by dbuenzli** [comment]
I have something in b3a61847c11b2d.

Note that the mecanism will break any tags functions that are in place (and will be broken if another library fiddles with them). 

I tried thinking about a scheme to preserve tags functions but that would entail creating a new non-gc'd closure on each `set_*` and could lead to multiple functions being called in chain for lookup and we want the latter to be fast and thus be a single function call away.

As far as I'm concerned the tags mechanism should be deprecated anyway.

**Comment by Drup** [comment]
> As far as I'm concerned the tags mechanism should be deprecated anyway.

It's better to have a good replacement before deprecating something. At the moment, we don't.

**Comment by dbuenzli** [comment]
> It's better to have a good replacement before deprecating something.

Well the mechanism is impossible to use in a compositional fashion and is based on an ad-hoc and wrong idea so better not lure people into using it and deprecate it immediately. It will save time for everybody. I also don't think that it's being used in practice and if it is, I can't help thinking it must be for a wrong reason --- the same way I subvert it for achieving an orthogonal goal.

It would be very easy to actually provide a high-level API to allow to associate client provided private typed data in a `format` value using a [data store](http://mlton.org/PropertyList) baked by a universal type. But as far as I'm concerned I'm no longer interested in interacting with the standard library "gatekeepers", I don't have the time an energy for that, and besides I don't think the latter "gatekeepers" are actually interested in improving the standard library in a *meaningful* way.
