### ISSUE TITLE
Easy Fmt.set_utf_8 and Fmt.style_renderer setup

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/fmt#7]
In a separate package fmt.unix package.

**Comment by dbuenzli** [comment]
Done in 4a3b5645d108b42d896e33, [API](http://erratique.ch/software/fmt/doc/Fmt_tty.html).

**Comment by Drup** [comment]
What about `strf` ? We may still want utf8 there.

**Comment by dbuenzli** [comment]
> What about strf ? We may still want utf8 there.

In fact `utf_8` is `true` by [default](http://erratique.ch/software/fmt/doc/Fmt.html#VALutf_8) and `style_tags` are `` `None``. So this is what you'll get on `strf`. 

I don't think it's a good idea to tweak `Format.str_formatter`'s, as its results may not necessarily be used to write to `tty`s. In fact I'm thinking that maybe I should raise Invalid_argument if one tries to `Fmt.set_{utf_8,style_renderer}` on `Format.str_formatter` as this could be the cause of quite subtle bugs.

If you need to first go through a string before outputing on a `tty` then you should go through a custom buffer formatter see for example [here](https://github.com/dbuenzli/bos/blob/master/src/bos_os_arg.ml#L136-L149). Maybe I should add a function that allows to easily copy the parameters of a formatter to another one (e.g. formally in this example the utf_8 parameter is not setup according to what it may be in `ppf`). 

What do you think ?

**Comment by Drup** [comment]
I agree with you, but `strf` doesn't use `str_formatter`. It creates a new buffer and a formatter based on that.

**Comment by dbuenzli** [comment]
Ah I thought `asprintf` what using `str_formatter`. So basically it means nothing needs to be done then since the formatter of `asprintf` is never exposed. I still should document that properly though.

**Comment by Drup** [comment]
Providing a way to change those options would be nice, though.

**Comment by dbuenzli** [comment]
You can always define your own formatter as suggested above.

**Comment by Drup** [comment]
Yes, but I'm not sure that's the most common behavior expected.

**Comment by dbuenzli** [comment]
> Yes, but I'm not sure that's the most common behavior expected.

Could you please be more specific in your requests. What are you talking about ? What do you want exactly ?

**Comment by Drup** [comment]
I'm questioning whether the current default is the right one. The fact that strf doesn't use the global settings that is used by the stdout/stderr formatters may not be the behavior expected by the user.

Especially considering the code to create a buffer and use it as a formatter correctly is not exactly straightforward.

**Comment by dbuenzli** [comment]
> I'm questioning whether the current default is the right one. The fact that strf doesn't use the global settings that is used by the stdout/stderr formatters may not be the behavior expected by the user.

Well you can immediately see that nothing better can be done for `strf`: both `stdout` and `stderr` may be setup differently (e.g. `stdout` redirected to a file while `stderr` is not). 

> Especially considering the code to create a buffer and use it as a formatter correctly is not exactly straightforward.

Yes something should be provided like `for_ppf : Formatter -> ('a, Format.formatter, unit, string) Pervasives.format4 -> 'a`.
